### PR TITLE
Framework: Drop obsolete SSR stubs

### PR DESCRIPTION
**Pull request by ockham**
Counterpart to https://github.com/Automattic/wp-calypso/pull/22059, doesn't work yet.

### CODE REVIEW

**Comment by sirreal** [comment]
Cleaning up my queues, happy to review when this is ready 👍

**Comment by ockham** [comment]
Thanks folks. Last I checked, I couldn't get desktop to run with this branch 🙁  That might be circumstantial, I only manage to get wp-desktop to build and run every other or so time...

**Comment by ockham** [comment]
Rebased.

**Comment by nsakaimbo** [comment]
Stale - closing.

**Pull request closed without merging**
