### PR TITLE
Ping Pong!

### LINKED ISSUE #51: Calypso server persists after Electron crashes
From #45 via @johngodley:

This is an edge case: if Electron crashes, it requires a reboot to get the app working again because the server process is then not killed (you can kill -9 on the main process to simulate this). There isn't much we can do to handle the crash when it happens, but we can try to recover afterwards.

For example, we detect a server is already running when we start the app. If it is, maybe we can somehow re-attach rather than start. Alternatively, maybe the server process can occasionally ping the parent process - if it doesn't respond it kills itself.

### PR DESCRIPTION
**Pull request by mjangda**
Make the app send periodic pings to Calypso to make sure the server is still running. If we fail to get a response, we can detect that and handle accordingly.

Needs https://github.com/Automattic/wp-calypso/pull/3062 to work

Fixes #51

### CODE REVIEW

**Comment by mjangda** [comment]
We need to decide if `maybeKillswitch` should kill the calypso server or restart it.

Also, looks like there may be issues when going into screensaver or sleep mode.

**Comment by johngodley** [comment]
Seems to work although I've not been able to get the `Failed to get ping from Calypso; exiting.` message to appear (I may be doing something wrong, or the app exits before the message is shown). No processes are left behind.

What happens when the system goes to sleep - does the kill timer expire on wakeup?

**Comment by mjangda** [comment]
I can't reproduce the sleep issue now. I think it may have been something else.

Things I've tested:

### Kill Electron

- `make run`
- find pids using `ps aux | grep [e]lectron`
- `kill -9` the 2 main electron processes using the pids
- `ps aux | grep [e]lectron` shortly after and verify the `bundle-desktop.js` process is no longer running

### Kill Calypso

- `make run`
- find pid for `bundle-desktop.js` using `ps aux | grep [e]lectron`
- `kill -9` using the pid
- console shows the following:

```
desktop:server app.exit with code: 0 (SIGKILL) +2s
  desktop:server app.close with code: 0 (SIGKILL) +1ms
  desktop:server Failed to get ping from Calypso; exiting. +28s
  desktop:server Killing server +1ms
```

The window stays open and the app continues to mostly work (since it's an SPA :)) but breaks if you log out. In this instance, it would be nice if we could gracefully restart the server, or show an error to the user.

**Comment by mjangda** [comment]
No longer necessary as of #66

**Pull request closed without merging**
