### PR TITLE
Fix error icons and preload

### PR DESCRIPTION
**Pull request by johngodley**
Fix missing error icons

Move app setup into preload

### CODE REVIEW

**Comment by spen** [comment]
It seems that the `boot` test is failing - investigating this now :)

**Comment by spen** [comment]
I've found it difficult to track down the exact reason but it seems that either the event or listener that sends `is-calypso` or `is-calypso-response` is not firing/listening.

I remember having issues tracing the sender of `is-calypso` in my previous tasks - @johngodley do you know where this comes from?
The tests & listeners were introduced in #43 if that helps.

**Comment by johngodley** [comment]
Ah, I forgot about the tests. I can't remember where anything comes from so I'll look into this some more!

**Comment by johngodley** [comment]
@spen the new `preload.js` wasn't being included in the built file so it wasn't starting Calypso - unit test FTW! I've moved it into the public_desktop directory and it works locally for me

**Comment by astralbodies** [comment]
There's a merge conflict @johngodley - are you able to check it out and see how to resolve it?

**Comment by astralbodies** [comment]
Thanks!!

**Pull request merged**
