### PR TITLE
[e2e] Fix logout issue in e2e tests

### PR DESCRIPTION
**Pull request by Stojdza**
### Description:
Update e2e tests with `return` at the end of every step. This change fixes the logout issue (logout step was disabled in https://github.com/Automattic/wp-desktop/pull/694/commits/2509f864d7a05f36c9cb0638efafcdee935f24d2). 

### Motivation and Context:
Logout of the app in e2e tests was inconsistent - it didn't pass all the times, and tests were flaky. 

### How Has This Been Tested:
Run e2e tests locally or re-run the CircleCI job in this PR. They should be green.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey @Stojdza! Thank you for looking into this! 
I run the tests locally multiple times and I had no issues. Though, the first time I re-run the workflow on CI I got a failure on the logout test. 
I'm not trying to re-run it again in order to keep the current state in case it helps you.

**Comment by Stojdza** [comment]
Thanks @loremattei! Yeah, unfortunately, it looks like the same issue. I'll take a look more closely. But, I had a feeling it fails less often than before 🤞

**Comment by Stojdza** [comment]
After merging the latest changes from `develop`, tests are [consistently passing on CircleCI](https://circleci.com/gh/Automattic/workflows/wp-desktop/tree/fix%2Fe2e%2Flogout-issue). But locally, I see sometimes log out is still failing.

**Comment by nsakaimbo** [comment]
Thanks for continuing to poke at this, @Stojdza ! Fixing the stability of our tests is definitely a goal this year. The changes look reasonable - I'll try to give it a spin when I get some time. 

> But locally, I see sometimes log out is still failing.

Curiously, how are you invoking the tests locally? Have you been able to run all the tests locally, or just this one?

**Comment by Stojdza** [comment]
> Curiously, how are you invoking the tests locally? Have you been able to run all the tests locally, or just this one?

I'm running them with `mocha test/tests/e2e.js` command.  Yes, I run all e2e locally, and only clicking on the Log Out button is inconsistent. I wonder is it related to the sidebar and how it loads? For example, in tests, I tried to click on "Account Settings" instead Log Out button, and it's the same - sometimes it passes sometimes it doesn't.

**Comment by nsakaimbo** [comment]
@Stojdza What account are you using to run the tests? I just encountered a strange thing that I still don't quite understand. I've never been able to runt the tests locally using a dummy account and blog I set up for testing. What I found was, with my dummy account, the CSS selectors expected in the tests were different. 

A couple of days ago, I used the exact same credentials locally as we use on CI, and the tests worked and were consistent. I have no idea why this would be the case - it seems the tests depend on an account being configured in a very exact way.

You could try the CI credentials instead and see if they give you different results when running locally.

**Comment by Stojdza** [comment]
> What account are you using to run the tests?
I created one account through the desktop app for testing purposes and I was using only that account. 

> What I found was, with my dummy account, the CSS selectors expected in the tests were different.
This is really strange and unexpected! Maybe that could explain some odd behaviors in tests executions 😬

**Comment by Stojdza** [comment]
🤞

**Comment by bsessions85** [comment]
@Stojdza  Looks good! Hopefully this will boost the stability and add more coverage.

**Pull request merged**
