### PR TITLE
Use flat modules and disable asar

### PR DESCRIPTION
**Pull request by johngodley**
This disables asar packing and uses NPM 3 flat modules to package the app up.

#50

### CODE REVIEW

**Comment by mkaz** [comment]
It does not run on Windows, I see the `Failed to start the app` error dialog

The console is giving me:

```
Error: Cannot find module 'bundler/assets'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\marcu\Desktop\WordPress.com-win32-ia32\resources\app\calypso\build\bundle-desktop.js:25098:19)
    at __webpack_require__ (C:\Users\marcu\Desktop\WordPress.com-win32-ia32\resources\app\calypso\build\bundle-desktop.js:21:30)
    at setup (C:\Users\marcu\Desktop\WordPress.com-win32-ia32\resources\app\calypso\build\bundle-desktop.js:132:13)
    at Object.<anonymous> (C:\Users\marcu\Desktop\WordPress.com-win32-ia32\resources\app\calypso\build\bundle-desktop.js:66:12)
    at __webpack_require__ (C:\Users\marcu\Desktop\WordPress.com-win32-ia32\resources\app\calypso\build\bundle-desktop.js:21:30)
    at C:\Users\marcu\Desktop\WordPress.com-win32-ia32\resources\app\calypso\build\bundle-desktop.js:41:18
```

**Comment by mjangda** [comment]
I think might be related to the having the wrong `cwd` set (at least, that's how I remember fixing it last time on OSX).

**Comment by johngodley** [comment]
@mkaz, I can't reproduce that particular error. Are you sure you are running NPM version 3+?

**Comment by mkaz** [comment]
Yep, using version `3.3.12` of npm

Here's the process I just went through again to build
```
$ git checkout  update/revenge-of-child-spawning-server-from-hell
$ git pull
$ git submodule update
$ cd calypso; rm -rf node_modules
$ make build
$ cd ..; rm -rf node_modiles
$ npm install
$ make build
$ make win32
```

Copied the Windows release directory over to the VM and ran from Windows PowerShell command-line and see the same error.

**Comment by johngodley** [comment]
Should now work on Windows and Linux

**Comment by mjangda** [comment]
Woohoo!

**Comment by mkaz** [comment]
First issue, shortcut (and initial launch) for Windows does not work. Launching from command-line does. The error message received on first launch, or via the shortcut: 

screen shot 2016-01-28 at 9 10 54 am

**Comment by mkaz** [comment]
Second issue, Windows is popping up a Firewall alert on launch. I checked briefly and looks like host is specified as 127.0.0.1, which should be allowed. Mac likely will do something similar if host is not specified and listening on 0.0.0.0

screen shot 2016-01-28 at 9 27 32 am

**Comment by mjangda** [comment]
Windows failures are due to the `console.log` calls in Calypso when booting and the `morgan` middleware. If you remove those, app runs as expected.

**Pull request merged**
