### PR TITLE
Documentation: Correct a secrets link.

### PR DESCRIPTION
**Pull request by kwight**
This PR corrects the link to detailed instructions for generating secrets required for development.

**Testing Instructions**
Verify the updated link in `docs/install.md` takes you to `docs/secrets.md`, instead of a GitHub 404.

### CODE REVIEW

**Comment by mmtr** [comment]
Thanks @kwight, the change looks ok to me 👍. 

Do you know why this PR would merge 17 commits? Not sure if this needs a rebase or if we should target another branch instead of `develop`. /cc @loremattei

**Comment by loremattei** [comment]
Yep! Thank you @kwight!

I think this branch has been created from `master`. `develop` looks like the right target, so it probably needs a rebase.

**Comment by gwwar** [comment]
Might be easier remaking this from `develop`, unless folks want to try stepping through with the rebase.

**Comment by kwight** [comment]
Will redo from `develop`.

**Pull request closed without merging**
