### PR TITLE
Use pug instead of Jade

### LINKED ISSUE #372: Build: Issues with pug
I tried using the wp-calypso branch that updates from `jade` to `pug` as the `calypso` checkout on the `develop` branch (https://github.com/Automattic/wp-calypso/pull/19984#pullrequestreview-77751470).

I see the following error when I attempt to build (`make distclean; npm i; make run`):

```
Error: Cannot find module 'pug'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/jonsurrell/a8c/wp-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at new View (/Users/jonsurrell/a8c/wp-desktop/build/node_modules/express/lib/view.js:80:30)
    at Function.render (/Users/jonsurrell/a8c/wp-desktop/build/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/Users/jonsurrell/a8c/wp-desktop/build/node_modules/express/lib/response.js:971:7)
    at serverRenderError (/Users/jonsurrell/a8c/wp-desktop/build/desktop.js:78224:8)
    at Layer.handle_error (/Users/jonsurrell/a8c/wp-desktop/build/node_modules/express/lib/router/layer.js:71:5)
```

cc/ @ockham

### PR DESCRIPTION
**Pull request by ockham**
Fixes #372 

To test -- Verify that the app buillds and runs fine.

### CODE REVIEW

**Comment by sirreal** [comment]
Let's leave it for @astralbodies to merge when the calypso module is updated.

**Comment by ockham** [comment]
> Let's leave it for @astralbodies to merge when the calypso module is updated.

I'm cool with that; tho the PR does include the [submodule bump](https://github.com/Automattic/wp-desktop/pull/373/files#diff-95f292773550fc8d39aaa8ddc9f3cfac), just sayin'.

**Comment by astralbodies** [comment]
Merged in develop to fix the unit tests and we're good to merge. Thanks @sirreal!

**Comment by sirreal** [comment]
And especially @ockham 😀

**Comment by astralbodies** [comment]
Oops - that's who I meant hahaha - thanks @ockham!

**Pull request merged**
